### ISSUE TITLE
Prebuild binarys of headless chromium

### ISSUE THREAD

**Issue by FWeinb** [samccone/headless-snap#3]
I don't know if this would be the right place to do it. But it would be great to have pre build binaries of the required headless chromium.

**Comment by samccone** [comment]
Unfortunately a bin distribution is not something that I can provide.

Luckily i made a handy dandy guide here:
https://docs.google.com/document/d/1a9cdsljKxCSreR2LDE3KErJhfyC0N9y5ju2UYZb8-J4/edit#

And if someone were to host the bin somewhere I do not think anyone would be up in arms about it.

**Comment by paulirish** [comment]
@FWeinb i have a slightly older build that i'll send your way.

**Comment by FWeinb** [comment]
@samccone 
Thanks will look into that guide. 

@paulirish 
Awesome, thanks!
